# Generated by Django 4.1 on 2025-11-13 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegraCrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_regra', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('crase_obrigatoria', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Regras de Crase',
            },
        ),
        migrations.CreateModel(
            name='TermoRegente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True)),
                ('tipo_regente', models.CharField(choices=[('Verbo', 'Verbo'), ('Nome', 'Nome'), ('LocucaoPrepositiva', 'Locução Prepositiva')], max_length=50)),
                ('exige_preposicao', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermoRegido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(max_length=100, unique=True)),
                ('classe_gramatical', models.CharField(choices=[('Substantivo', 'Substantivo'), ('Pronome', 'Pronome'), ('LocucaoAdverbial', 'Locução Adverbial')], max_length=50)),
                ('genero', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino')], max_length=10)),
                ('aceita_artigo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MapeamentoCrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('regente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craseapp.termoregente')),
                ('regido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craseapp.termoregido')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='craseapp.regracrase')),
            ],
            options={
                'verbose_name': 'Mapeamento de Crase',
                'verbose_name_plural': 'Mapeamentos de Crase',
                'unique_together': {('regente', 'regido')},
            },
        ),
    ]
